services:
  - type: web
    name: video-conference-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
